/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.103
 * Generated at: 2020-03-27 10:22:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class calculator_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


int x=3;
int y=4;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("input{\r\n");
      out.write("\twidth:50px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("}\r\n");
      out.write(".output{\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tbackground: #e9e9e9;\r\n");
      out.write("\tfont-size:24px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("\tpadding: 0px 5px;\t\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"calc3\" method=\"post\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"output\" colspan=\"4\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x+y}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"operator\" value=\"CE\"/></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"operator\" value=\"C\"/></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"operator\" value=\"BS\"/></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"operator\" value=\"/\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"value\" value=\"7\"/></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"value\" value=\"8\"/></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"value\" value=\"9\"/></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"operator\" value=\"*\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"value\" value=\"4\"/></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"value\" value=\"5\"/></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"value\" value=\"6\"/></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"operator\" value=\"-\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"value\" value=\"1\"/></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"value\" value=\"2\"/></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"value\" value=\"3\"/></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"operator\" value=\"+\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"value\" value=\"0\"/></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"operator\" value=\".\"/></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" name=\"operator\" value=\"=\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
